apiVersion: v1
kind: ConfigMap
metadata:
  name: kapacitor-alerts
  namespace: kube-system
data:
  high_cpu.tick: |
    stream
        |from()
            .measurement('cpu/usage_rate')
            .groupBy('nodename')
        |window()
            .period(1m)
            .every(1m)
        |mean('value').as('used')
        |alert()
            .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "nodename" }} has high cpu usage: {{ index .Fields "used" }}')
            .warn(lambda: "used" > 70.0)
            .crit(lambda: "used" > 85.0)
            .email()
