apiVersion: v1
kind: ConfigMap
metadata:
  name: kapacitor-alerts
  namespace: kube-system
data:
  high_cpu.tick: |
    stream
        |from()
            .measurement('cpu_usage_idle')
            .groupBy('host')
        |window()
            .period(1m)
            .every(1m)
        |mean('value')
        |eval(lambda: 100.0 - "mean")
            .as('used')
        |alert()
            .message('{{ .Level}}: {{ .Name }}/{{ index .Tags "host" }} has high cpu usage: {{ index .Fields "used" }}')
            .warn(lambda: "used" > 70.0)
            .crit(lambda: "used" > 85.0)
