apiVersion: v1
kind: SystemApplication
metadata:
  name: monitoring-app
  repository: gravitational.io
  namespace: kube-system
  resourceVersion: 0.0.3
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-install
      spec:
        template:
          metadata:
            name: monitoring-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:0.0.1
                command: ["/usr/local/bin/kubectl", "apply", "-f", "/var/lib/gravity/resources/resources.yaml"]
  update:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-update
      spec:
        parallelism: 1
        completions: 1
        activeDeadlineSeconds: 100
        template:
          metadata:
            name: monitoring-app-update
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: monitoring-hook:0.0.1
                args: ["update"]
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-uninstall
      spec:
        template:
          metadata:
            name: monitoring-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:0.0.1
                command: ["/usr/local/bin/kubectl", "delete", "-f", "/var/lib/gravity/resources/resources.yaml"]
