apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: kube-system
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/web/grafana
    [auth.anonymous]
    org_role = Admin
