apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: heapster
    name: heapster
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
  template:
    metadata:
      labels:
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: monitoring-heapster:1.0.2
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default.svc.cluster.local?kubeletPort=10250&kubeletHttps=true
        - --sink=influxdb:http://influxdb:8086
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
    nodePort: 32500
  selector:
    k8s-app: heapster
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: influxdb
  name: influxdb
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: influxdb
  template:
    metadata:
      labels:
        name: influxdb
    spec:
      containers:
      - name: influxdb
        image: monitoring-influxdb:0.13.0
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        hostPath:
          path: /var/lib/data/influxdb
---
apiVersion: v1
kind: Service
metadata:
  labels: null
  name: influxdb
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http
    port: 8083
    nodePort: 32501
  - name: api
    port: 8086
    nodePort: 32502
  selector:
    name: influxdb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: grafana
    name: grafana
  name: grafana
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: monitoring-grafana:3.0.4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Grafana
  name: grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: grafana
    port: 3000
    nodePort: 32503
  selector:
    app: grafana
